// Copyright (c) 2025 Komodo Platform
// This is the main entry point for the Komodo UI Kit
//
// DO NOT MANUALLY EDIT.
// The indexes can be generated by running `dart run index_generator`

/// Higher-order component compositions
library fuego_ui.composite;

export 'cards/collapsible_card.dart';
